# https://docs.github.com/en/actions/tutorials/create-actions/create-a-composite-action
name: 'Docker action'
inputs:
    distro:
        required: true
    push:
        required: true
    registry_username:
        required: false
    registry_password:
        required: false
runs:
    using: "composite"
    steps: # https://github.com/marketplace/actions/build-and-push-docker-images
        - uses: actions/checkout@v5
        - run: git config --remove-section 'http.https://github.com/'
          shell: bash
        # - uses: docker/setup-qemu-action@v3
        - uses: docker/setup-buildx-action@v3
        - uses: docker/login-action@v3
          if: ${{ inputs.push == 'true' }}
          with:
            username: ${{ inputs.registry_username }}
            password: ${{ inputs.registry_password }}

        - uses: docker/build-push-action@v6
          with:
            file: ccws/examples/Dockerfile
            context: .
            push: ${{ inputs.push }}
            tags: asherikov/ccws_${{ inputs.distro }}:latest,asherikov/ccws_${{ inputs.distro }}:${{ github.ref_name }}
            build-args: "BASE_IMAGE=ubuntu:${{ inputs.distro }}"

