#!/bin/bash
set -e
#echo ">>>>> CCWS cmake wrapper >>>>>>"
#pwd
#echo "Command line: $@"
# shellcheck disable=SC2086
proot --rootfs="${CCWS_SYSROOT}" \
    --cwd="$(pwd)" \
    ${IFS# profile specific args} \
    ${CCWS_PROOT_ARGS} \
    ${IFS# workspace and compiler} \
    --bind="${CCWS_WORKSPACE_DIR}" \
    ${IFS# installation paths} \
    --bind="${CCWS_INSTALL_DIR_HOST}:${CCWS_INSTALL_DIR_TARGET}" \
    --bind=/lib/udev/rules.d \
    ${IFS# bind mounting of /bin/ breaks stuff for some reason} \
    --bind=/bin/true \
    --bind=/bin/false \
    --bind=/bin/echo \
    --bind=/bin/ls \
    --bind=/bin/ln \
    --bind=/bin/sh \
    --bind=/bin/rm \
    --bind=/bin/pwd \
    --bind=/bin/bash \
    --bind=/bin/uname \
    --bind=/bin/mktemp \
    --bind=/usr/bin/env \
    --bind=/usr/bin/perl \
    --bind=/usr/bin/make \
    ${IFS# python bindings} \
    --bind=/usr/bin/python \
    --bind=/usr/bin/python3 \
    $(find /usr/lib/ -maxdepth 1 -name "python*" | sed "s/^/--bind=/" | paste -s -d ' ') \
    ${IFS# cmake bindings} \
    --bind=/usr/bin/cmake \
    $(find /usr/share/ -maxdepth 1 -name "cmake*" | sed "s/^/--bind=/" | paste -s -d ' ') \
    "/usr/bin/cmake" "$@"
#echo "<<<<< CCWS cmake wrapper <<<<<<"
#exit 1
