#!/bin/bash
source ${CCWS_PROOT_BIN}/common.bash

#echo ">>>>> CCWS cmake wrapper >>>>>>"
#pwd
#echo "Command line: $@"
# shellcheck disable=SC2086
proot --rootfs="${CCWS_SYSROOT}" \
    --cwd="$(pwd)" \
    ${IFS# profile specific args} \
    ${CCWS_PROOT_ARGS} \
    ${IFS# workspace and compiler} \
    --bind="${WORKSPACE_DIR}" \
    ${IFS# installation paths} \
    --bind="${CCWS_INSTALL_DIR_BUILD}:${CCWS_INSTALL_DIR_HOST}" \
    --bind=/lib/udev/rules.d \
    ${IFS# suppress annoying ld warnings} \
    --bind="/dev/null:/etc/ld.so.preload" \
    ${IFS# bind mounting of /bin/ breaks stuff for some reason} \
    --bind=/bin/true \
    --bind=/bin/false \
    --bind=/bin/echo \
    --bind=/bin/ls \
    --bind=/bin/ln \
    --bind=/bin/sh \
    --bind=/bin/rm \
    --bind=/bin/pwd \
    --bind=/bin/bash \
    --bind=/bin/uname \
    --bind=/bin/mktemp \
    --bind=/usr/bin/env \
    --bind=/usr/bin/perl \
    --bind=/usr/bin/make \
    ${IFS# python bindings (only if the same ROS distro is installed on the build system)} \
    $(test ! -d /opt/ros/${ROS_DISTRO} || find /usr/bin/ /usr/lib/ -maxdepth 1 -name "python*" | sed "s/^/--bind=/" | paste -s -d ' ') \
    ${IFS# cmake bindings} \
    --bind=/usr/bin/cmake \
    $(find /usr/share/ -maxdepth 1 -name "cmake*" | sed "s/^/--bind=/" | paste -s -d ' ') \
    "/usr/bin/cmake" "$@"
#echo "<<<<< CCWS cmake wrapper <<<<<<"
#exit 1

