#!/bin/bash
source ${CCWS_PROOT_BIN}/common.bash

set -e

#echo ">>>>> CCWS rosdep wrapper >>>>>>"
#pwd
#echo "Command line: $@"
# shellcheck disable=SC2086

# detect OS and override rosdep autodection
# http://wiki.ros.org/ROS/EnvironmentVariables#ROS_OS_OVERRIDE
if [ -z "${ROS_OS_OVERRIDE}" ]
then
    ROS_OS_OVERRIDE=$(proot \
        ${IFS# common args} \
        ${CCWS_PROOT_ARGS} \
        "/usr/bin/lsb_release" -rsci | paste -d ':' -s | tr '[:upper:]' '[:lower:]')
    export ROS_OS_OVERRIDE
fi

/usr/bin/rosdep "$@"

#echo "<<<<< CCWS rosdep wrapper <<<<<<"
#exit 1
