FROM asherikov/ccws_noble:latest

ENV APT_INSTALL="env DEBIAN_FRONTEND=noninteractive apt --yes --no-install-recommends install"
ENV PIP3_INSTALL="python3 -m pip install"

ARG SANDBOX_NAME="qwen-code-sandbox"
ARG CLI_VERSION_ARG
ENV SANDBOX="$SANDBOX_NAME"
ENV CLI_VERSION=$CLI_VERSION_ARG


# Import NodeSource GPG key and add repository for Node.js
RUN wget -qO - https://deb.nodesource.com/setup_20.x | sudo bash

# Install dependencies
RUN \
--mount=type=cache,target=/var/cache/apt,sharing=locked \
--mount=type=cache,target=/var/lib/apt/lists/,sharing=locked \
--mount=type=cache,target=/cache/pip,sharing=locked \
    apt update \
    && apt upgrade -y \
    && ${APT_INSTALL} nodejs \
    && ${APT_INSTALL} \
        man-db \
        curl \
        dnsutils \
        jq \
        bc \
        gh \
        ripgrep \
        procps \
        psmisc \
        lsof \
        socat

# Set up npm global package folder
RUN mkdir -p /usr/local/share/npm-global
ENV NPM_CONFIG_PREFIX=/usr/local/share/npm-global
ENV PATH=$PATH:/usr/local/share/npm-global/bin

RUN npm install -g @qwen-code/qwen-code

# Default entrypoint when none specified
CMD ["qwen"]
