ARG BASE_IMAGE=asherikov/ccws_noble:latest
FROM ${BASE_IMAGE}

ENV APT_INSTALL="env DEBIAN_FRONTEND=noninteractive apt --yes --no-install-recommends install"
ENV PIPX_INSTALL="python3 -m pipx install"


# Install dependencies
RUN \
--mount=type=cache,target=/var/cache/apt,sharing=locked \
--mount=type=cache,target=/var/lib/apt/lists/,sharing=locked \
--mount=type=cache,target=/cache/pip,sharing=locked \
    apt update \
    && apt upgrade -y \
    && ${APT_INSTALL} \
        man-db \
        curl \
        dnsutils \
        jq \
        bc \
        gh \
        ripgrep \
        procps \
        psmisc \
        lsof \
        socat

USER ccws

# Install opencode
# uses x64 instead of amd64
RUN curl -fsSL \
        "https://github.com/anomalyco/opencode/releases/latest/download/opencode-linux-x64.tar.gz" \
    | tar -xz -C /ccws/ccws/tools/bin/

# Default entrypoint when none specified
CMD ["tmux", "-u", "new-session", "opencode"]
