#!/bin/bash
set -e
#echo ">>>>> CCWS rosdep wrapper >>>>>>"
#pwd
#echo "Command line: $@"
# shellcheck disable=SC2086
proot --rootfs="${CCWS_SYSROOT}" \
    ${IFS# profile specific args} \
    ${CCWS_PROOT_ARGS} \
    ${IFS# rosdep stuff} \
    --bind="${ROS_HOME}/rosdep/:${ROS_HOME}/rosdep" \
    --bind=/etc/ros/rosdep/ \
    ${IFS# bind mounting of /bin/ breaks stuff for some reason} \
    --bind=/bin/true \
    --bind=/bin/false \
    --bind=/bin/echo \
    --bind=/bin/ls \
    --bind=/bin/ln \
    --bind=/bin/sh \
    --bind=/bin/rm \
    --bind=/bin/pwd \
    --bind=/bin/bash \
    --bind=/bin/uname \
    --bind=/bin/mktemp \
    --bind=/usr/bin/env \
    --bind=/usr/bin/perl \
    --bind=/usr/bin/cmake \
    --bind=/usr/bin/make \
    ${IFS# python bindings} \
    --bind=/usr/bin/python \
    --bind=/usr/bin/python3 \
    $(find /usr/lib/ -maxdepth 1 -name "python*" | sed "s/^/--bind=/" | paste -s -d ' ') \
    ${IFS# qemu} \
    --qemu="qemu-${CCWS_TRIPLE_ARCH}" \
    --cwd="${CCWS_WORKSPACE_DIR}" \
    "${CCWS_HOST_ROOT}/usr/bin/python" "${CCWS_HOST_ROOT}/usr/bin/rosdep" "$@"
#echo "<<<<< CCWS rosdep wrapper <<<<<<"
#exit 1
